version: '3'

services:
  user_auth_service:
    build: ./user_auth_service
    ports:
      - "9000:9000"
    depends_on:
      - mysql
  useradminservice:
    build: ./UserAdminService
    ports:
      - "9001:9001"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"