version: '3'

services:
  user_auth_service:
    build: ./user_auth_service
    container_name: user_auth_service_container
    ports:
      - "9000:9000"
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:5.7
    container_name: mysql_db_container
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
